steps:
  # Paso 1: Construir la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-node-apps/zoho-sync-job:$SHORT_SHA'
      - '.'

  # Paso 2: Empujar la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-node-apps/zoho-sync-job:$SHORT_SHA'

# Especificar la imagen final
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-node-apps/zoho-sync-job:$SHORT_SHA'

# Opciones de la compilación para evitar el error
options:
  logging: CLOUD_LOGGING_ONLY